---
- name: Web Development VM configuration play
  hosts: all
  remote_user: root
  become: yes
  tasks:
  - name: Install necessary packages.
    apt: name={{ item }} state=present
    with_items:
      - curl
      - git
      - build-essential
      - apt-transport-https
      - ca-certificates
      - apparmor
      - linux-image-extra-{{ ansible_kernel }}
      - vim
      - linux-image-extra-virtual
      - software-properties-common

  - name: Set Time Zone.
    copy: content='America/Santo_Domingo'
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
    notify:
      - Update timezone

  - name: Add GPG key for Docker installation.
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

  - name: Add Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      state: present
      filename: 'docker'

  - name: Install Docker engine
    apt:
      name: docker-ce
      state: present

  - name: Ensure Docker service is started
    service: name=docker state=started

  - name: Ensure Docker service is started.
    service: name=docker state=started

  - name: Add docker group.
    group: name=docker state=present

  - name: Add vagrant user to docker group.
    user: name=vagrant groups=docker append=yes

  handlers:
    - name: Update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

    - name: Restart Docker daemon
      service: name=docker state=restarted

# This play install Docker Compose.
- name: Docker Compose installation
  hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.14.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: 0775

    - name: Install command line completion for Docker Compose.
      shell: curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
      args:
        creates: /etc/bash_completion.d/docker-compose
