---
- name: Web Development VM configuration play
  hosts: all
  remote_user: root
  become: yes
  tasks:
  - name: Ensure Git PPA is added.
    apt_repository: repo='ppa:git-core/ppa' state=present
  - name: Ensure git and other packages are installed.
    apt: name={{ item }} state=latest update_cache=yes cache_valid_time=604800
    with_items:
      - curl
      - git
      - build-essential
      - apt-transport-https
      - ca-certificates
      - apparmor
      - linux-image-extra-{{ ansible_kernel }}
      - vim
  - name: Set Time Zone
    copy: content='America/Santo_Domingo'
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
    notify:
      - update timezone
  - name: Add GPG key for Docker.
    apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  - name: Add debian repo for Docker.
    shell: echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list
    args:
      creates: /etc/apt/sources.list.d/docker.list
  - name: Ensure Docker is installed.
    apt: name=docker-engine state=latest update_cache=yes
  - name: Ensure Docker service is started.
    service: name=docker state=started
  - name: Add docker group.
    group: name=docker state=present
  - name: Add vagrant user to docker group.
    user: name=vagrant groups=docker append=yes
  - name: Ensure Docker Compose is installed.
    get_url:
      url: https://github.com/docker/compose/releases/download/1.8.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 0775
  - name: Install command line completion for Docker Compose.
    shell: curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
    args:
      creates: /etc/bash_completion.d/docker-compose
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
